# Generated by Django 4.0.3 on 2022-05-02 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('article', models.TextField()),
                ('Date de publication', models.DateField(default=datetime.date.today)),
                ('publication', models.CharField(choices=[('SP', 'Sciences Po'), ('ML', 'La manche libre')], default='SP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enfance', models.BooleanField()),
                ('Portrait', models.BooleanField()),
                ('Reportage', models.BooleanField()),
                ('Enquête', models.BooleanField()),
            ],
        ),
    ]
