# Generated by Django 4.0.3 on 2022-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0002_theme_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.TextField(default='1 - : \n2 - : \n3 - : \n4 - : \n...'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(default=None),
        ),
    ]
