# Generated by Django 4.0.3 on 2022-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0003_article_source_alter_article_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='Etude',
            field=models.BooleanField(default=False),
        ),
    ]
