# Generated by Django 4.0.3 on 2022-05-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0007_remove_article_auteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Source')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ArticlePage.article')),
            ],
        ),
    ]
