# Generated by Django 4.0.3 on 2022-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0008_remove_article_source_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='item',
            field=models.CharField(default=None, max_length=200, verbose_name='Source'),
        ),
    ]
