# Generated by Django 4.1 on 2023-01-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0011_remove_theme_ef_remove_theme_en_remove_theme_et_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='themes',
            field=models.ManyToManyField(blank=True, to='ArticlePage.theme'),
        ),
    ]
