# Generated by Django 4.1 on 2023-01-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0012_remove_theme_article_article_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.CharField(choices=[('SP', 'Sciences Po'), ('ML', 'La manche libre'), ('OF', 'Ouest France'), ('EP', 'Ecrits personnels')], default='SP', max_length=2, verbose_name='Publication'),
        ),
    ]
