# Generated by Django 4.0.3 on 2022-05-10 21:57

import PodcastPage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('author', models.CharField(max_length=50, verbose_name='Auteur')),
                ('audio', models.FileField(upload_to=PodcastPage.models.directory_path, verbose_name='Fichier du podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO', models.BooleanField(verbose_name='Portrait')),
                ('RE', models.BooleanField(verbose_name='Reportage')),
                ('ET', models.BooleanField(verbose_name='Etude')),
                ('MT', models.BooleanField(verbose_name='Micro trottoir')),
                ('DI', models.BooleanField(verbose_name='Discussion')),
                ('podcast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PodcastPage.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Chapitres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Titre du chapitre')),
                ('timestamp', models.TimeField(verbose_name='Début du chapitre à')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PodcastPage.podcast')),
            ],
        ),
    ]
