# Generated by Django 4.0.3 on 2022-05-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PodcastPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapitres',
            new_name='Chapitre',
        ),
    ]
