# Generated by Django 4.1 on 2022-09-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PodcastPage', '0002_rename_chapitres_chapitre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['title']},
        ),
    ]
