# Generated by Django 4.0.3 on 2022-05-07 01:56

import CVPage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CVPage', '0002_alter_projects_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du projet')),
                ('link', models.URLField(max_length=100, null=True, verbose_name='Lien vers le projet')),
                ('photo', models.ImageField(upload_to=CVPage.models.user_directory_path, verbose_name='Photo du projet')),
            ],
        ),
        migrations.RenameModel(
            old_name='Experiences',
            new_name='Experience',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='name',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='cv',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(max_length=100, null=True, verbose_name='Lien du réseau'),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AddField(
            model_name='project',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVPage.cv'),
        ),
    ]
