# Generated by Django 4.0.3 on 2022-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVPage', '0003_project_rename_experiences_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_fin',
            field=models.DateField(null=True, verbose_name='Date de fin'),
        ),
    ]
