# Generated by Django 4.0.3 on 2022-05-09 00:57

import CVPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVPage', '0004_alter_experience_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='entreprise',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Lien vers le projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to=CVPage.models.make_file_path, verbose_name='Photo du projet'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Lien du réseau'),
        ),
        migrations.AlterField(
            model_name='social',
            name='nom',
            field=models.CharField(choices=[('GH', 'github'), ('TW', 'twitter'), ('IN', 'instagram'), ('FB', 'facebook'), ('LN', 'linkedin')], max_length=2, verbose_name='Nom du réseau'),
        ),
    ]
