# Generated by Django 4.0.3 on 2022-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVPage', '0005_alter_experience_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(default=None, max_length=100, verbose_name='Lien du réseau'),
        ),
    ]
